local highlight = require("latex_concealer.extmark").config.highlight
return {
	--Greek
	["alpha"] = { "α", highlight.greek },
	["beta"] = { "β", highlight.greek },
	["gamma"] = { "γ", highlight.greek },
	["delta"] = { "δ", highlight.greek },
	["epsilon"] = { "ϵ", highlight.greek },
	["varepsilon"] = { "ε", highlight.greek },
	["zeta"] = { "ζ", highlight.greek },
	["eta"] = { "η", highlight.greek },
	["theta"] = { "θ", highlight.greek },
	["vartheta"] = { "ϑ", highlight.greek },
	["iota"] = { "ι", highlight.greek },
	["kappa"] = { "κ", highlight.greek },
	["lambda"] = { "λ", highlight.greek },
	["mu"] = { "μ", highlight.greek },
	["nu"] = { "ν", highlight.greek },
	["xi"] = { "ξ", highlight.greek },
	["pi"] = { "π", highlight.greek },
	["varpi"] = { "ϖ", highlight.greek },
	["rho"] = { "ρ", highlight.greek },
	["varrho"] = { "ϱ", highlight.greek },
	["sigma"] = { "σ", highlight.greek },
	["varsigma"] = { "ς", highlight.greek },
	["tau"] = { "τ", highlight.greek },
	["upsilon"] = { "υ", highlight.greek },
	["phi"] = { "ϕ", highlight.greek },
	["varphi"] = { "φ", highlight.greek },
	["chi"] = { "χ", highlight.greek },
	["psi"] = { "ψ", highlight.greek },
	["omega"] = { "ω", highlight.greek },
	["Gamma"] = { "Γ", highlight.greek },
	["Delta"] = { "Δ", highlight.greek },
	["Theta"] = { "Θ", highlight.greek },
	["Lambda"] = { "Λ", highlight.greek },
	["Xi"] = { "Ξ", highlight.greek },
	["Pi"] = { "Π", highlight.greek },
	["Sigma"] = { "Σ", highlight.greek },
	["Upsilon"] = { "Υ", highlight.greek },
	["Phi"] = { "Φ", highlight.greek },
	["Chi"] = { "Χ", highlight.greek },
	["Psi"] = { "Ψ", highlight.greek },
	["Omega"] = { "Ω", highlight.greek },
	--Special
	["exists"] = { "∃", highlight.symbol },
	["forall"] = { "∀", highlight.symbol },
	["models"] = { "╞", highlight.symbol },
	["S"] = { "§", highlight.symbol },
	["vdots"] = { "⋮", highlight.symbol },
	["angle"] = { "∠", highlight.symbol },
	["cdots"] = { "⋯", highlight.symbol },
	["ddots"] = { "⋱", highlight.symbol },
	["dots"] = { "…", highlight.symbol },
	["ldots"] = { "…", highlight.symbol },
	["natural"] = { "♮", highlight.symbol },
	["flat"] = { "♭", highlight.symbol },
	["sharp"] = { "♯", highlight.symbol },
	["clubsuit"] = { "♣", highlight.symbol },
	["diamondsuit"] = { "♢", highlight.symbol },
	["heartsuit"] = { "♡", highlight.symbol },
	["spadesuit"] = { "♠", highlight.symbol },
	["imath"] = { "ɩ", highlight.symbol },
	["jmath"] = { "𝚥", highlight.symbol },
	["emptyset"] = { "∅", highlight.symbol },
	["varnothing"] = { "∅", highlight.symbol },
	["hbar"] = { "ℏ", highlight.symbol },
	["ell"] = { "ℓ", highlight.symbol },
	["infty"] = { "∞", highlight.symbol },
	["aleph"] = { "ℵ", highlight.symbol },
	["wp"] = { "℘", highlight.symbol },
	["wr"] = { "≀", highlight.symbol },
	["\\"] = { "", highlight.symbol },
	["{"] = { "{", highlight.delim },
	["}"] = { "}", highlight.delim },
	--debackslash
	["sgn"] = { "sgn", highlight.operatorname },
	["max"] = { "max", highlight.operatorname },
	["min"] = { "min", highlight.operatorname },
	["lim"] = { "lim", highlight.operatorname },
	["sin"] = { "sin", highlight.operatorname },
	["cos"] = { "cos", highlight.operatorname },
	["tan"] = { "tan", highlight.operatorname },
	["cot"] = { "cot", highlight.operatorname },
	["arcsin"] = { "arcsin", highlight.operatorname },
	["gcd"] = { "gcd", highlight.operatorname },
	["deg"] = { "deg", highlight.operatorname },
	["exp"] = { "exp", highlight.operatorname },
	["sup"] = { "sup", highlight.operatorname },
	["inf"] = { "inf", highlight.operatorname },
	["d"] = { "d", highlight.operatorname },
	["ln"] = { "ln", highlight.operatorname },
	["log"] = { "log", highlight.operatorname },
	--Operator
	["rceil"] = { "⌉", highlight.delim },
	["lceil"] = { "⌈", highlight.delim },
	["lfloor"] = { "⌊", highlight.delim },
	["rfloor"] = { "⌋", highlight.delim },
	["langle"] = { "⟨", highlight.delim },
	["rangle"] = { "⟩", highlight.delim },
	["cap"] = { "∩", highlight.operator },
	["cdot"] = { "·", highlight.operator },
	["circ"] = { "∘", highlight.operator },
	["cup"] = { "∪", highlight.operator },
	["div"] = { "÷", highlight.operator },
	["land"] = { "∧", highlight.operator },
	["lor"] = { "∨", highlight.operator },
	["mp"] = { "∓", highlight.operator },
	["nabla"] = { "∇", highlight.operator },
	["neg"] = { "¬", highlight.operator },
	["odot"] = { "⊙", highlight.operator },
	["ominus"] = { "⊖", highlight.operator },
	["oplus"] = { "⊕", highlight.operator },
	["oslash"] = { "⊘", highlight.operator },
	["otimes"] = { "⊗", highlight.operator },
	["partial"] = { "∂", highlight.operator },
	["pm"] = { "±", highlight.operator },
	["Re"] = { "ℜ", highlight.operator },
	["Im"] = { "ℑ", highlight.operator },
	["setminus"] = { "∖", highlight.operator },
	["sqcap"] = { "⊓", highlight.operator },
	["sqcup"] = { "⊔", highlight.operator },
	["times"] = { "×", highlight.operator },
	["triangle"] = { "∆", highlight.operator },
	["vee"] = { "∨", highlight.operator },
	["wedge"] = { "∧", highlight.operator },
	["amalg"] = { "∐", highlight.operator },
	["coprod"] = { "∐", highlight.operator },
	["asymp"] = { "≍", highlight.relationship },
	["approx"] = { "≈", highlight.relationship },
	["rightleftharpoons"] = { "⇌", highlight.relationship },
	--Huge Operator
	["bigcap"] = { "∩", highlight.hugeoperator },
	["bigcirc"] = { "○", highlight.hugeoperator },
	["bigcup"] = { "∪", highlight.hugeoperator },
	["bigodot"] = { "⊙", highlight.hugeoperator },
	["bigoplus"] = { "⊕", highlight.hugeoperator },
	["bigotimes"] = { "⊗", highlight.hugeoperator },
	["bigsqcup"] = { "⊔", highlight.hugeoperator },
	["bigtriangledown"] = { "∇", highlight.hugeoperator },
	["bigtriangleup"] = { "∆", highlight.hugeoperator },
	["bigvee"] = { "⋁", highlight.hugeoperator },
	["bigwedge"] = { "⋀", highlight.hugeoperator },
	["int"] = { "∫", highlight.hugeoperator },
	["oint"] = { "∮", highlight.hugeoperator },
	["iint"] = { "∬", highlight.hugeoperator },
	["oiint"] = { "∯", highlight.hugeoperator },
	["iiint"] = { "∭", highlight.hugeoperator },
	["oiiint"] = { "∰", highlight.hugeoperator },
	["iiiint"] = { "∬∬", highlight.hugeoperator },
	["idotsint"] = { "∫⋯∫", highlight.hugeoperator },
	["prod"] = { "∏", highlight.hugeoperator },
	["sum"] = { "∑", highlight.hugeoperator },
	--arrows
	["implies"] = { "⇒", highlight.arrow }, --re
	["mapsto"] = { "↦", highlight.arrow },
	["Downarrow"] = { "⇓", highlight.arrow },
	["nearrow"] = { "↗", highlight.arrow },
	["nwarrow"] = { "↖", highlight.arrow },
	["searrow"] = { "↘", highlight.arrow },
	["swarrow"] = { "↙", highlight.arrow },
	["Uparrow"] = { "⇑", highlight.arrow },
	["updownarrow"] = { "↕", highlight.arrow },
	["Updownarrow"] = { "⇕", highlight.arrow },
	["to"] = { "→", highlight.arrow }, --re
	["uparrow"] = { "↑", highlight.arrow }, --re
	["rightarrow"] = { "→", highlight.arrow }, --re
	["Rightarrow"] = { "⇒", highlight.arrow }, --re
	["leftarrow"] = { "←", highlight.arrow }, --re
	["Leftarrow"] = { "⇐", highlight.arrow }, --re
	["leftharpoondown"] = { "↽", highlight.arrow }, --re
	["leftharpoonup"] = { "↼", highlight.arrow }, --re
	["leftrightarrow"] = { "↔", highlight.arrow }, --re
	["Leftrightarrow"] = { "⇔", highlight.arrow }, --re
	["gets"] = { "←", highlight.arrow }, --re
	["iff"] = { "⇔", highlight.arrow }, --re
	["downarrow"] = { "↓", highlight.arrow }, --re
	["hookleftarrow"] = { "↩", highlight.arrow },
	["hookrightarrow"] = { "↪", highlight.arrow },
	--relationship
	["bot"] = { "⊥", highlight.relationship }, --re
	["cong"] = { "≅", highlight.relationship }, --re
	["doteq"] = { "≐", highlight.relationship }, --re
	["equiv"] = { "≡", highlight.relationship }, --re
	["ge"] = { "≥", highlight.relationship }, --re
	["geq"] = { "≥", highlight.relationship }, --re
	["in"] = { "∈", highlight.relationship }, --re
	["le"] = { "≤", highlight.relationship }, --re
	["leq"] = { "≤", highlight.relationship }, --re
	["ll"] = { "≪", highlight.relationship }, --re
	["mid"] = { "∣", highlight.relationship }, --re
	["ne"] = { "≠", highlight.relationship }, --re
	["neq"] = { "≠", highlight.relationship }, --re
	["ni"] = { "∋", highlight.relationship }, --re
	["nmid"] = { "∤", highlight.relationship },
	["notin"] = { "∉", highlight.relationship }, --re
	["owns"] = { "∋", highlight.relationship }, --re
	["parallel"] = { "║", highlight.relationship }, --re
	["perp"] = { "⊥", highlight.relationship }, --re
	["prec"] = { "≺", highlight.relationship }, --re
	["preceq"] = { "⪯", highlight.relationship }, --re
	["propto"] = { "∝", highlight.relationship }, --re
	["sim"] = { "∼", highlight.relationship }, --re
	["simeq"] = { "⋍", highlight.relationship }, --re
	["sqsubset"] = { "⊏", highlight.relationship }, --re
	["sqsubseteq"] = { "⊑", highlight.relationship }, --re
	["sqsupset"] = { "⊐", highlight.relationship }, --re
	["sqsupseteq"] = { "⊒", highlight.relationship }, --re
	["subset"] = { "⊂", highlight.relationship }, --re
	["subseteq"] = { "⊆", highlight.relationship }, --re
	["succ"] = { "≻", highlight.relationship }, --re
	["succeq"] = { "⪰", highlight.relationship }, --re
	["supset"] = { "⊃", highlight.relationship }, --re
	["supseteq"] = { "⊇", highlight.relationship }, --re
	["vdash"] = { "⊢", highlight.relationship }, --re
	--others
	["|"] = { "‖", highlight.delim },
	["lVert"] = { "‖", highlight.delim },
	["rVert"] = { "‖", highlight.delim },
	["ast"] = { "∗", highlight.symbol },
	["backslash"] = { "∖", highlight.symbol },
	["bowtie"] = { "⋈", highlight.symbol },
	["bullet"] = { "•", highlight.symbol },
	["copyright"] = { "©", highlight.symbol },
	["dagger"] = { "†", highlight.symbol },
	["dashv"] = { "⊣", highlight.symbol },
	["ddagger"] = { "‡", highlight.symbol },
	["diamond"] = { "⋄", highlight.symbol },
	["frown"] = { "⁔", highlight.symbol },
	["gg"] = { "⟫", highlight.symbol },
	["lmoustache"] = { "╭", highlight.symbol },
	["P"] = { "¶", highlight.symbol },
	["prime"] = { "′", highlight.symbol },
	["quad"] = { " ", highlight.symbol },
	["qquad"] = { " ", highlight.symbol },
	["rmoustache"] = { "╮", highlight.symbol },
	["smile"] = { "‿", highlight.symbol },
	["star"] = { "✫", highlight.symbol },
	["surd"] = { "√", highlight.symbol },
	["top"] = { "⊤", highlight.symbol },
	["triangleleft"] = { "⊲", highlight.symbol },
	["triangleright"] = { "⊳", highlight.symbol },
	["lvert"] = { "|", highlight.delim },
	["rvert"] = { "|", highlight.delim },
	["ae"] = { "æ", highlight.symbol },
	["nolinebreak"] = { "🧲", highlight.symbol },
}
